#!/usr/bin/env python

from sys import argv
from sys import exit
from Bio import SeqIO
from Bio.Alphabet import generic_dna, generic_protein

USAGE = "Usage: fasta2genbank <input.fa> <output.gb>"

if len(argv) != 3:
    print(USAGE)
    exit(1)

input_handle = open(argv[1], "rU")
output_handle = open(argv[2], "w")

sequences = list(SeqIO.parse(input_handle, "fasta"))

#asign generic_dna or generic_protein
for seq in sequences:
  seq.seq.alphabet = generic_dna

count = SeqIO.write(sequences, output_handle, "genbank")

output_handle.close()
input_handle.close()
print "Coverted %i records" % count
