#!/usr/bin/env python

from sys import argv

def parse_blatoutput(output_psl):
    for i in range(5):
	output_psl.readline()
    for line in output_psl:
        line = line.strip().split('\t')
	name_chr = line[13]
	start = line[15]
	end = line[16]
	blocksize = line[18]
	block_position= line[19]
	name_query = line[9]
	strand = line[8][1]
 	print '\t'.join([name_chr, start, end, name_query, "100", strand, start, end, "255,0,0", blocksize, block_position]) 


if __name__ == "__main__":
    if len(argv) == 1:
        print("Usage: psil2bed <input.psl> <output.bed>")
    output_psl = open(argv[1], 'r')
    parse_blatoutput(open(argv[1], 'r')) 

    
